---
- name: Install Node.js using ansible-nodejs-role
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: ansible-nodejs-role
  vars:
    nodejs_version: "22.x"
    nodejs_nodesource_pin_priority: 600
